version 4.11
#include "zscript/Weapons.zs"
#include "zscript/B3DPlayer.zs"
#include "zscript/nashmove.zs"
#include "zscript/DoorsOpener.zs"
#include "zscript/BaseDecoration.zs"
#include "zscript/BaseLamp.zs"
#include "zscript/BaseFoe.zs"
#include "zscript/generated/include.zs"
